# See https://wiki.hyprland.org/Configuring/Binds/
#!
##! User
bind = Ctrl+Super, Period, exec, xdg-open ~/.config/chima/config.json # Edit shell config
bind = Ctrl+Super+Alt, Period, exec, xdg-open ~/.config/hypr/custom/keybinds.conf # Edit extra keybinds

# Add stuff here
# Use #! to add an extra column on the cheatsheet
# Use ##! to add a section in that column
# Add a comment after a bind to add a description, like above

unbind = Super, 1
unbind = Super, 2
unbind = Super, 3
unbind = Super, 4
unbind = Super, 5
unbind = Super, 6
unbind = Super, 7
unbind = Super, 8
unbind = Super, 9
unbind = Super, 0
unbind = Super, V
unbind = Super, C
unbind = Super, W
unbind = Super, X
unbind = Super+Shift, W

##! Workspace + App Shortcuts
bind = Super, 1, exec, ~/.config/hypr/custom/scripts/launcher.sh 1 "ghostty" "com.mitchellh.ghostty" # Focus workspace 1 (Terminal)
bind = Super, 2, workspace, 2 # Focus workspace 2
bind = Super, V, exec, ~/.config/hypr/custom/scripts/launcher.sh 2 "vivaldi" "vivaldi" # Focus workspace 2 (Vivaldi)
bind = Super, Z, exec, ~/.config/hypr/custom/scripts/launcher.sh 2 "zen-browser" "zen" # Focus workspace 2 (Zen Browser)
bind = Super, 3, workspace, 3 # Focus workspace 3
bind = Super, X, exec, ~/.config/hypr/custom/scripts/launcher.sh 3 "kitty -e fish -c 'source ~/.ssh/ssh-agent-env 2>/dev/null; nvim'" "kitty" # Focus workspace 3 (NeoVim)
bind = Super, C, exec, ~/.config/hypr/custom/scripts/launcher.sh 3 "code" "code" # Focus workspace 3 (VSCode)
bind = Super, 4, exec, ~/.config/hypr/custom/scripts/launcher.sh 4 "obsidian --disable-gpu --disable-software-rasterizer --ozone-platform-hint=auto" "obsidian" # Focus workspace 4 (Obsidian)
bind = Super, 5, exec, ~/.config/hypr/custom/scripts/launcher.sh 5 "lens-desktop" "lens" # Focus workspace 5 (Lens)
bind = Super, 6, exec, ~/.config/hypr/custom/scripts/launcher.sh 6 "beekeeper-studio" "/opt/Beekeeper Studio/beekeeper-studio" # Focus workspace 6 (Beekeeper Studio)
bind = Super, 7, exec, ~/.config/hypr/custom/scripts/launcher.sh 7 "slack" "slack" # Focus workspace 7 (Slack)
bind = Super, 8, exec, ~/.config/hypr/custom/scripts/launcher.sh 8 "$HOME/.local/share/applications/WhatsApp-linux-x64/WhatsApp" "WhatsApp" && ~/.config/hypr/custom/scripts/launcher.sh 8 "flatpak run com.discordapp.Discord" "discord" # Focus workspace 8 (WhatsApp & Discord)
bind = Super, 9, workspace, 9 # Focus workspace 9
bind = Super, 0, workspace, 10 # Focus workspace 10

##! Window Movement
# Move window to workspace
bind = Super+Shift, 1, movetoworkspace, 1 # Move to workspace 1
bind = Super+Shift, 2, movetoworkspace, 2 # Move to workspace 2
bind = Super+Shift, 3, movetoworkspace, 3 # Move to workspace 3
bind = Super+Shift, 4, movetoworkspace, 4 # Move to workspace 4
bind = Super+Shift, 5, movetoworkspace, 5 # Move to workspace 5
bind = Super+Shift, 6, movetoworkspace, 6 # Move to workspace 6
bind = Super+Shift, 7, movetoworkspace, 7 # Move to workspace 7
bind = Super+Shift, 8, movetoworkspace, 8 # Move to workspace 8
bind = Super+Shift, 9, movetoworkspace, 9 # Move to workspace 9
bind = Super+Shift, 0, movetoworkspace, 10 # Move to workspace 10


