# See https://wiki.hyprland.org/Configuring/Binds/
#!
##! User
bind = Ctrl+Super, Period, exec, xdg-open ~/.config/chima/config.json # Edit shell config
bind = Ctrl+Super+Alt, Period, exec, xdg-open ~/.config/hypr/custom/keybinds.conf # Edit extra keybinds

# Add stuff here
# Use #! to add an extra column on the cheatsheet
# Use ##! to add a section in that column
# Add a comment after a bind to add a description, like above

# We use raw keycodes because some keyboard layouts (like ABNT2) register number keys as different chars
# The codes can be verified with `wev`
unbind = Super, V # Overriding clipboard toggle from main-keybinds.conf

##! Workspace + App Shortcuts
bind = Super, code:10, exec, ~/.config/hypr/custom/scripts/launcher.sh 1 "ghostty" "com.mitchellh.ghostty" # Focus workspace 1 (Terminal)
bind = Super, code:11, workspace, 2 # Focus workspace 2
bind = Super, V, exec, ~/.config/hypr/custom/scripts/launcher.sh 2 "vivaldi" "vivaldi" # Focus workspace 2 (Vivaldi)
bind = Super, Z, exec, ~/.config/hypr/custom/scripts/launcher.sh 2 "zen-browser" "zen" # Focus workspace 2 (Zen Browser)
bind = Super, code:12, workspace, 3 # Focus workspace 3
bind = Super, X, exec, ~/.config/hypr/custom/scripts/launcher.sh 3 "kitty -e fish -c 'source ~/.ssh/ssh-agent-env 2>/dev/null; nvim'" "kitty" # Focus workspace 3 (NeoVim)
bind = Super, C, exec, ~/.config/hypr/custom/scripts/launcher.sh 3 "code" "code" # Focus workspace 3 (VSCode)
bind = Super, code:13, exec, ~/.config/hypr/custom/scripts/launcher.sh 4 "obsidian --disable-gpu --disable-software-rasterizer --ozone-platform-hint=auto" "obsidian" # Focus workspace 4 (Obsidian)
bind = Super, code:14, exec, ~/.config/hypr/custom/scripts/launcher.sh 5 "lens-desktop" "lens" # Focus workspace 5 (Lens)
bind = Super, code:15, exec, ~/.config/hypr/custom/scripts/launcher.sh 6 "beekeeper-studio" "/opt/Beekeeper Studio/beekeeper-studio" # Focus workspace 6 (Beekeeper Studio)
bind = Super, code:16, exec, ~/.config/hypr/custom/scripts/launcher.sh 7 "slack" "slack" # Focus workspace 7 (Slack)
bind = Super, code:17, exec, ~/.config/hypr/custom/scripts/launcher.sh 8 "$HOME/.local/share/applications/WhatsApp-linux-x64/WhatsApp" "WhatsApp" && ~/.config/hypr/custom/scripts/launcher.sh 8 "flatpak run com.discordapp.Discord" "discord" # Focus workspace 8 (WhatsApp & Discord)
bind = Super, code:18, workspace, 9 # Focus workspace 9
bind = Super, code:19, workspace, 10 # Focus workspace 10

##! Window Movement
# Move window to workspace
bind = Super+Shift, code:10, movetoworkspace, 1 # Move to workspace 1
bind = Super+Shift, code:11, movetoworkspace, 2 # Move to workspace 2
bind = Super+Shift, code:12, movetoworkspace, 3 # Move to workspace 3
bind = Super+Shift, code:13, movetoworkspace, 4 # Move to workspace 4
bind = Super+Shift, code:14, movetoworkspace, 5 # Move to workspace 5
bind = Super+Shift, code:15, movetoworkspace, 6 # Move to workspace 6
bind = Super+Shift, code:16, movetoworkspace, 7 # Move to workspace 7
bind = Super+Shift, code:17, movetoworkspace, 8 # Move to workspace 8
bind = Super+Shift, code:18, movetoworkspace, 9 # Move to workspace 9
bind = Super+Shift, code:19, movetoworkspace, 10 # Move to workspace 10


