$text_color = rgba(FFFFFFFF)
$entry_background_color = rgba(FFFFFF26)
$entry_border_color = rgba(FFFFFF00)
$entry_color = rgba(FFFFFFFF)
$font_family = Rubik
$font_family_clock = Rubik
$font_material_symbols = Material Symbols Rounded

background {
    monitor =
    path = $HOME/.config/hypr/hyprlock-wallpaper.png
    color = rgba(25, 20, 20, 1.0)
    blur_passes = 3
    blur_size = 5
    brightness = 0.8
}

input-field {
    monitor =
    size = 230, 30
    outline_thickness = 0
    dots_size = 0.2
    dots_spacing = 0.3
    outer_color = $entry_border_color
    inner_color = $entry_background_color
    font_color = $entry_color
    fade_on_empty = true
    font_family = $font_family
    font_size = 12
    position = 0, -80
    halign = center
    valign = center
    check_color = $entry_background_color
    fail_color = rgba(FF5555FF)
    capslock_color = $entry_background_color
    numlock_color = $entry_background_color
    bothlock_color = $entry_background_color
    invert_numlock = false
    swap_font_color = false
}

image {
    monitor =
    path = $HOME/Pictures/Profile.jpg
    size = 120
    rounding = -1
    border_size = 0
    position = 0, 40
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] date +'%H:%M:%S • %d/%m/%Y'
    color = $text_color
    font_size = 11
    font_family = $font_family
    position = 0, -10
    halign = center
    valign = top
}

label {
    monitor =
    text = cmd[update:3600000] getent passwd $USER | cut -d: -f5
    color = $text_color
    font_size = 13
    font_family = $font_family
    font_weight = 800
    position = 0, -45
    halign = center
    valign = center
}