#!/usr/bin/env bash

# Hypridle configuration manager
# Reads and writes hypridle.conf settings

HYPRIDLE_CONF="${XDG_CONFIG_HOME:-$HOME/.config}/hypr/hypridle.conf"

# Function to get current timeout values
get_timeouts() {
    if [ ! -f "$HYPRIDLE_CONF" ]; then
        # Return defaults if file doesn't exist
        echo "LOCK_TIMEOUT=300"
        echo "DPMS_TIMEOUT=600"
        echo "SUSPEND_TIMEOUT=900"
        return
    fi

    # Parse the file for timeout values
    lock_timeout=$(grep -A2 "on-timeout = loginctl lock-session" "$HYPRIDLE_CONF" | grep "timeout =" | sed 's/.*timeout = \([0-9]*\).*/\1/')
    dpms_timeout=$(grep -A2 "on-timeout = hyprctl dispatch dpms off" "$HYPRIDLE_CONF" | grep "timeout =" | sed 's/.*timeout = \([0-9]*\).*/\1/')
    suspend_timeout=$(grep -A2 "on-timeout = \$suspend_cmd" "$HYPRIDLE_CONF" | grep "timeout =" | sed 's/.*timeout = \([0-9]*\).*/\1/')

    # Use defaults if not found
    [ -z "$lock_timeout" ] && lock_timeout=300
    [ -z "$dpms_timeout" ] && dpms_timeout=600
    [ -z "$suspend_timeout" ] && suspend_timeout=900

    echo "LOCK_TIMEOUT=$lock_timeout"
    echo "DPMS_TIMEOUT=$dpms_timeout"
    echo "SUSPEND_TIMEOUT=$suspend_timeout"
}

# Function to set new timeout values
set_timeouts() {
    local lock_timeout=$1
    local dpms_timeout=$2
    local suspend_timeout=$3
    local enable_lock=${4:-1}
    local enable_dpms=${5:-1}
    local enable_suspend=${6:-1}

    if [ ! -f "$HYPRIDLE_CONF" ]; then
        echo "Error: hypridle.conf not found at $HYPRIDLE_CONF" >&2
        exit 1
    fi

    # Create backup
    cp "$HYPRIDLE_CONF" "$HYPRIDLE_CONF.bak"

    # Read the suspend command from the original file
    suspend_cmd=$(grep '^\$suspend_cmd' "$HYPRIDLE_CONF" | head -1)
    lock_cmd=$(grep '^\$lock_cmd' "$HYPRIDLE_CONF" | head -1)

    # Use defaults if not found
    [ -z "$suspend_cmd" ] && suspend_cmd='$suspend_cmd = systemctl suspend || loginctl suspend'
    [ -z "$lock_cmd" ] && lock_cmd='$lock_cmd = pidof hyprlock || hyprlock'

    # Write new configuration
    cat > "$HYPRIDLE_CONF" << EOF
# Generated by hypridle-manager.sh
# You can edit this file manually, but changes may be overwritten by the settings app

$lock_cmd
$suspend_cmd

general {
    lock_cmd = \$lock_cmd
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch global quickshell:lockFocus
    inhibit_sleep = 3
}

EOF

    # Add lock listener if enabled and timeout > 0
    if [ "$enable_lock" = "1" ] && [ "$lock_timeout" -gt 0 ]; then
        cat >> "$HYPRIDLE_CONF" << EOF
listener {
    timeout = $lock_timeout
    on-timeout = loginctl lock-session
}

EOF
    fi

    # Add DPMS listener if enabled and timeout > 0
    if [ "$enable_dpms" = "1" ] && [ "$dpms_timeout" -gt 0 ]; then
        cat >> "$HYPRIDLE_CONF" << EOF
listener {
    timeout = $dpms_timeout
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

EOF
    fi

    # Add suspend listener if enabled and timeout > 0
    if [ "$enable_suspend" = "1" ] && [ "$suspend_timeout" -gt 0 ]; then
        cat >> "$HYPRIDLE_CONF" << EOF
listener {
    timeout = $suspend_timeout
    on-timeout = \$suspend_cmd
}

EOF
    fi

    echo "Hypridle configuration updated successfully"
}

# Main script logic
case "${1}" in
    --get)
        get_timeouts
        ;;
    --set)
        if [ $# -lt 7 ]; then
            echo "Usage: $0 --set <lock_timeout> <dpms_timeout> <suspend_timeout> <enable_lock> <enable_dpms> <enable_suspend>" >&2
            exit 1
        fi
        set_timeouts "$2" "$3" "$4" "$5" "$6" "$7"
        ;;
    *)
        echo "Usage: $0 {--get|--set <lock_timeout> <dpms_timeout> <suspend_timeout> <enable_lock> <enable_dpms> <enable_suspend>}" >&2
        exit 1
        ;;
esac
